CREATE TABLE IF NOT EXISTS kullanici (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 kullanici_adi VARCHAR(255),
sifre VARCHAR(255),
email VARCHAR(255));
CREATE TABLE IF NOT EXISTS mesaj (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
mesaj_icerigi VARCHAR(1000));
CREATE TABLE IF NOT EXISTS sohbet_odasi(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
oda_adi VARCHAR(255));